swagger: '2.0'
info:
  version:
  title:
  license:
    name:
paths:
  /app/version:
    get:
      summary: 获取最新版本情况
      tags:
      - 公共模块
      operationId: commonVersion
      parameters:
      - name: platform
        in: query
        description: 平台 android：安卓 ios：ios
        type: string
      - name: app_version
        in: query
        description: 当前版本号，如:1.0.1
        type: string
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "",
                "data": [
                    "Andaman Nicobar",
                    "Andhra Pradesh",
                    "Arunachal Pradesh",
                    "Assam",
                    "Bihar",
                    "Chandigarh",
                    "Chhattisgarh",
                    "Dadra Nagar Haveli",
                    "Daman Diu",
                    "Delhi",
                    "Goa",
                    "Gujarat",
                    "Haryana",
                    "Himachal Pradesh",
                    "Jammu Kashmir",
                    "Jharkhand",
                    "Karnataka",
                    "Kerala",
                    "Lakshadweep",
                    "Madhya Pradesh",
                    "Maharashtra",
                    "Manipur",
                    "Meghalaya",
                    "Mizoram",
                    "Nagaland",
                    "Odisha",
                    "Puducherry",
                    "Punjab",
                    "Rajasthan",
                    "Sikkim",
                    "Tamil Nadu",
                    "Telangana",
                    "Tripura",
                    "Uttar Pradesh",
                    "Uttarakhand",
                    "West Bengal"
                ]
            }
  /app/city/residential-city:
    get:
      summary: residential city城市选择
      tags:
      - 公共模块
      operationId: commonCityResidentialCity
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "获取成功",
                "data": {
                    "open_city": [
                        "Bangalore",
                        "Mumbai",
                        "Hyderabad",
                        "Pune",
                        "Chennai"
                    ],
                    "city_list": [
                        {
                            "city": "Adilabad",
                            "status": 1
                        },
                        {
                            "city": "Agar Malwa",
                            "status": 1
                        },
                    ]
                }
            }

  /app/captcha/send-sms:
    post:
      summary: 发送短信验证码 (弃用)
      tags:
      - 验证码模块
      operationId: sendSms
      parameters:
      - name: telephone
        in: query
        description: 手机号
        type: string
        required: true
      - name: use
        in: query
        description: 方法use， 登录验证：app_login  忘记密码forgot_password
        type: string
        default: app_login
        required: false
      responses:
        200:
          description: |
            {
              "code": 18000,
              "msg": "The OTP has sent to your mobile phone.",
              "data": ""
            }

  /app/captcha/send-email:
    post:
      summary: 发送邮箱验证码
      tags:
      - 验证码模块
      operationId: sendMail
      parameters:
      - name: email
        in: query
        description: email
        type: string
      responses:
        200:
          description: |
            {
              "code": 18000,
              "msg": "The OTP has sent to your mobile phone.",
              "data": ""
            }

  /app/captcha/send-voice:
    post:
      summary: 发送语音验证码
      tags:
      - 验证码模块
      operationId: sendVoice
      parameters:
      - name: telephone
        in: query
        description: telephone
        type: string
      responses:
        200:
          description: |
            {
              "code": 18000,
              "msg": "The OTP has sent to your mobile phone.",
              "data": ""
            }
  /app/notice:
    get:
      summary: APP通知公告（CRM）
      tags:
      - 公共模块
      operationId: notice
      parameters:
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "",
                "data": {
                    "notice": "sdfadfadf"
                }
            }
