swagger: '2.0'
paths:
  /api/collection_deduction/info:
    get:
      summary: 减免信息
      tags:
      - 催收管理
      operationId: collectionDeductionView
      parameters:
      - name: collection_id
        in: query
        description: 催收ID
        type: string
        required: true
      - name: repayment_plan_id
        in: query
        description: 还款计划ID
        type: string
      responses:
        200:
          description: |
            order.principal 应还本金
            order.overdue_fee 逾期息费
            deduction_mode 减免方式
            now_reduction_fee 减免金额
            can_deduction_amount 最多可减免
            now_deduction_start 减免有效期开始
            now_deduction_end 减免有效期结束
            减免后应还金额 应还本金+逾期息费-减免金额 (实时计算)

            {
              "code": 18000,
              "msg": "",
              "data": {
                "id": 1,
                "admin_id": 1,
                "user_id": 1,
                "order_id": 1,
                "status": "collectioning",
                "deduction_mode": "逾期息费减免",
                "now_deduction_start": "2018-11-11",
                "now_deduction_end": "2019-11-11",
                "now_reduction_fee": "100.00",
                "id_text": null,
                "status_text": "催收中",
                "order": {
                  "id": 1,
                  "order_no": "88412695C518B56888",
                  "user_id": 1,
                  "principal": "1000.00",
                  "loan_days": 30,
                  "status": "finish",
                  "created_at": "2019-01-31 10:53:23",
                  "app_client": "ios",
                  "app_version": "1.0.0",
                  "quality": 0,
                  "daily_rate": "0.0020",
                  "paid_time": "---",
                  "paid_amount": "940.00",
                  "pay_channel": "---",
                  "fullname": "钟富成",
                  "telephone": "18127820722",
                  "interest_fee": "60.00",
                  "overdue_fee": "0.00",
                  "reduction_fee": "100.00",
                  "receivable_amount": "900.00",
                  "pay_amount": "940.00",
                  "overdue_days": 0,
                  "appointment_paid_time": "2019-03-01 19:51:01",
                  "repay_time": "---",
                  "repay_amount": "0.00",
                  "bank_card_no": "6217002920131968100",
                  "bank_name": "建设银行",
                  "loan_location": "",
                  "loan_position": "113.953646,22.529468",
                  "channel": {
                    "id": 1,
                    "channel_code": "jqbwx",
                    "channel_name": "深圳金钱包公众号"
                  },
                  "order_no_text": null,
                  "status_text": "正常结清",
                  "app_client_text": "苹果",
                  "quality_text": "新用户",
                  "daily_rate_text": "0.2%",
                  "user": {
                    "id": 1,
                    "telephone": "18127820722",
                    "fullname": "钟富成",
                    "id_card_no": "440181199203034259",
                    "status": 1,
                    "created_at": "2019-01-21 12:39:18",
                    "updated_at": "2019-01-30 21:34:11",
                    "platform": "",
                    "client_id": "ios",
                    "channel_id": "1",
                    "quality": 0,
                    "app_version": "1.0.0",
                    "api_token": "",
                    "channel": {
                      "id": 1,
                      "channel_code": "jqbwx",
                      "channel_name": "深圳金钱包公众号"
                    }
                  },
                  "last_repayment_plan": {
                    "id": 1,
                    "user_id": 1,
                    "order_id": 1,
                    "no": "88698765C519014288",
                    "status": 1,
                    "overdue_days": 10,
                    "appointment_paid_time": "2019-03-01 19:51:01",
                    "repay_time": null,
                    "repay_amount": "0.00",
                    "repay_channel": "",
                    "reduction_fee": "100.00",
                    "created_at": "2019-02-01 15:27:20",
                    "updated_at": "2019-02-01 15:27:20",
                    "reduction_valid_date": "[\"2018-11-11\", \"2019-11-11\"]"
                  }
                },
                "collection_deduction": {
                  "id": 1,
                  "user_id": 1,
                  "order_id": 1,
                  "collection_id": 1,
                  "from_admin_id": 1,
                  "deduction_admin_id": 1,
                  "overdue_fee": "100.00",
                  "deduction": "100.00",
                  "status": 1,
                  "created_at": "2019-02-01 14:36:47",
                  "updated_at": "2019-02-01 14:37:18"
                }
              }
            }

  /api/collection_deduction/create:
    post:
      summary: 添加减免
      tags:
      - 催收管理
      operationId: collectionDeductionCreate
      parameters:
      - name: collection_id
        in: formData
        description: 催收ID
        type: integer
        required: true
      - name: repayment_plan_id
        in: formData
        description: 还款计划ID
        type: string
      - name: deduction
        in: formData
        description: 减免金额
        type: string
        required: true
      - name: deduction_time
        in: array
        description: 减免时间区间（Y-m-d）
        type: string
        required: true
      responses:
        200:
          description: |
            {
              "status": 0,
              "msg": "ok",
              "data": {

              }
            }
