swagger: '2.0'
info:
  version:
  title:
  license:
    name:
paths:
  /app/login:
    post:
      summary: 登录注册
      tags:
        - 登录模块
      operationId: login
      parameters:
        - name: telephone
          in: formData
          description: 电话号码
          type: string
          required: true
        - name: captcha
          in: formData
          description: 验证码(4位)
          type: string
          required: true
        - name: client_id
          in: query
          description: 注册终端
          type: string
          required: true
        - name: channel
          in: query
          description: 营销渠道
          type: string
        - name: platform
          in: formData
          description: 应用下载平台
          type: string
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "登录成功",
                "data": {
                    "token": "988b6583ce603d9899367a64bdd5446b",
                    "refresh_token": "a5637b9cb42332ab9f5e6dd3cab1fc0b"
                }
            }

  /app/re-login:
    post:
      summary: 登录续期(废弃)
      tags:
        - 登录模块
      operationId: reLogin
      parameters:
        - name: token
          in: formData
          description: 原token
          type: string
          required: true
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "登录续期成功",
                "data": {
                    "userId": 9,
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vc2Fhcy13YW5nc2wuZGV2MjMuaml1bWlhb2RhaS5jb20vcmUtbG9naW4iLCJpYXQiOjE1NTIzNjg4MjMsImV4cCI6MTU1NzU1Mjg3NSwibmJmIjoxNTUyMzY4ODc1LCJqdGkiOiIwUHZkTWh4VExlQ2Flc3dKIiwic3ViIjo5LCJwcnYiOiJhYTYzYzFlM2QwMDQwYjUyNTViMWRiYTZjM2I4MDY4MzA1MGRmMjFmIiwidmVyaWZ5X3VybCI6Imh0dHA6Ly8xMjAuNzcuMTk5LjY3OjgwMDEvdXNlci9ob21lIiwidG9rZW5fa2V5IjoidG9rZW4ifQ.731xKczH-DVYn7v6zUDiEWGoXuXb5Cjxp9wbpHESUNk",
                }
            }

  /app/send-sms-code:
    post:
      summary: 获取验证码
      tags:
        - 登录模块
      operationId: sendSmsCode
      parameters:
        - name: telephone
          in: formData
          description: 电话号码
          type: string
          required: true
        - name: use
          in: query
          description: 方法use， 登录验证：app_login  忘记密码forgot_password
          type: string
          default: app_login
          required: false
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "发送成功",
                "data": []
            }
  /app/logout:
    get:
      summary: 退出登录
      tags:
        - 登录模块
      operationId: logout
      parameters:
        - name: token
          in: query
          description: 令牌
          type: string
          required: true
      responses:
        200:
          description: |
            {
                "code": 18000,
                "msg": "退出登录成功",
                "data": []
            }
